name: Build
permissions:
  "contents": "write"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: |
          ./build-linux.sh
          ./build-windows.sh
          ./build-macos.sh
          mkdir release-artifacts
      - name: Compress
        run: |
          zip -r release-artifacts/Twitch-Developer-Announcement-Webhook-linux-x64.zip bin/Release/net8.0/linux-x64/publish/*
          zip -r release-artifacts/Twitch-Developer-Announcement-Webhook-linux-musl-x64.zip bin/Release/net8.0/linux-musl-x64/publish/*
          zip -r release-artifacts/Twitch-Developer-Announcement-Webhook-linux-musl-arm64.zip bin/Release/net8.0/linux-musl-arm64/publish/*
          zip -r release-artifacts/Twitch-Developer-Announcement-Webhook-linux-arm.zip bin/Release/net8.0/linux-arm/publish/*
          zip -r release-artifacts/Twitch-Developer-Announcement-Webhook-linux-arm64.zip bin/Release/net8.0/linux-arm64/publish/*
          zip -r release-artifacts/Twitch-Developer-Announcement-Webhook-win-x64.zip bin/Release/net8.0/win-x64/publish/*
          zip -r release-artifacts/Twitch-Developer-Announcement-Webhook-win-x86.zip bin/Release/net8.0/win-x86/publish/*
          zip -r release-artifacts/Twitch-Developer-Announcement-Webhook-win-arm64.zip bin/Release/net8.0/win-arm64/publish/*
          zip -r release-artifacts/Twitch-Developer-Announcement-Webhook-macos-x64.zip bin/Release/net8.0/osx-x64/publish/*
          zip -r release-artifacts/Twitch-Developer-Announcement-Webhook-macos-arm64.zip bin/Release/net8.0/osx-arm64/publish/*
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: Twitch-Developer-Announcement-Webhook
          path: release-artifacts
  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # allows for tags access
      - uses: actions/download-artifact@v6
        name: Download artifact
        with:
          name: Twitch-Developer-Announcement-Webhook
          path: release-artifacts/
      - name: Create release
        uses: ncipollo/release-action@v1.20.0
        with:
          replacesArtifacts: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "release-artifacts/*"
          body: ${{ github.event.head_commit.message }}
          prerelease: true
          name: Nightly Release
          tag: nightly-build
      - name: Update nightly-build tag
        run: |
          git tag -f nightly-build
          git push -f origin nightly-build
